CREATE DATABASE TableRelationsDB
GO

USE TableRelationsDB
GO

CREATE TABLE Persons(
	PersonID INT NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	Salary DECIMAL(15,2) NOT NULL,
	PassportID INT NOT NULL
)
GO

CREATE TABLE Passports(
	PassportID INT NOT NULL,
	PassportNumber VARCHAR(50) NOT NULL
)
GO

INSERT INTO Persons VALUES
(1, 'Roberto', 43300.00, 102),
(2, 'Tom', 56100.00, 103),
(3, 'Yana', 60200.00, 101)
GO

INSERT INTO Passports VALUES
(101, 'N34FG21B'),
(102, 'K65LO4R7'),
(103, 'ZE657QP2')
GO

ALTER TABLE Passports
ADD CONSTRAINT PK_Passports PRIMARY KEY(PassportID)
GO

ALTER TABLE Persons
ADD CONSTRAINT PK_Persons PRIMARY KEY(PersonID),
	CONSTRAINT FK_Persons_Passports FOREIGN KEY (PassportID) REFERENCES Passports(PassportID)
GO

USE master
GO

DROP DATABASE TableRelationsDB
GO